### ISSUE TITLE
Wrong hex conversion for offsets values

### ISSUE THREAD

**Issue by GeckoGB** [Myriadbits/MXFInspect#15]
Hi again,

Second bug i'm experiencing, is that if i change the settings to display the offsets in hex instead of decimal, the displayed values are completely wrong.

See the 2 pictures attached displaying the same part of the same file, in decimal and in hexadecimal.

For example value 34 949 439 086 becomes 0x34949439086 which is the same digits that the decimal values, but with a 0x appended and spaces removed.

Version 4.0.9.0 Windows 22H2.

Thanks again for your help!

Regards.

![GoodDecimalOffsets](https://user-images.githubusercontent.com/24299259/234080057-f69a4d69-8e7f-4057-9fc3-8ec141f467af.jpg)
![WrongHexOffsets](https://user-images.githubusercontent.com/24299259/234080080-ac2e83c3-41c3-43b4-8fe0-42ca149987ce.jpg)

**Comment by rayden84** [comment]
Hello and thank you for your bug report. Very much appreciated. I can confirm this and invite you to test if this [pre-release v4.1.2](https://github.com/Myriadbits/MXFInspect/releases/tag/v4.1.2) or even this release from my fork, that soon will be merged: [v4.1.8]( https://github.com/rayden84/MXFInspect/releases/tag/v4.1.8), still contains the bug.

**Comment by rayden84** [comment]
Closing as no feedback received.
