### ISSUE TITLE
SetTypePropertiesToReadOnly causes unwanted behavior

### ISSUE THREAD

**Issue by florianendrich** [Myriadbits/MXFInspect#8]
We adopted your work to on of our projects and came to an issuse regarding `SetTypePropertiesToReadOnly ` found in `MXFKLVFactory.cs`

https://github.com/Myriadbits/MXFInspect/blob/master/MXF/MXFKLVFactory.cs#L177

Our web application would not serialize the users post json as this methods sets every property to readonly via the `TypeDescriptionProvider`

as debuging shows your code here goes up to `System.Object`

```
SetTypePropertiesToReadOnly: System.Object
SetTypePropertiesToReadOnly: Myriadbits.MXF.MXFObject
SetTypePropertiesToReadOnly: Myriadbits.MXF.MXFKLV
SetTypePropertiesToReadOnly: Myriadbits.MXF.MXFMetadataBaseclass
SetTypePropertiesToReadOnly: Myriadbits.MXF.MXFInterchangeObject
SetTypePropertiesToReadOnly: Myriadbits.MXF.MXFGenericPackage
SetTypePropertiesToReadOnly: Myriadbits.MXF.MXFDescriptiveFramework
```

you might could add some check for `MXFObject` to prevent this.

thanks

**Comment by rayden84** [comment]
Dear @florianendrich, would you mind checking out if the issue also occurs for this fork:

https://github.com/rayden84/MXFInspect

It's a port for .NET6 of the original project, that I develop and try to keep active.
